### ISSUE TITLE
can not use this plugin with crosswalk

### ISSUE THREAD

**Issue by TechGuyVN** [munisense/cordova-plugin-local-storage-retrieval#1]
Dear Friend,

I have use this plugin with cordova & IONIC framework.
i use:
 cordova plugin add https://github.com/munisense/cordova-plugin-local-storage-retrieval

when run crosswalk, i can store data in localStorage normal, but when reset app, all variable lost.

Can you take investigate this problem.
Thanks !

**Comment by jeroenmaas** [comment]
Hi TechGuyVN,

Thank you for trying this plugin. Fortunately there is now a better solution to use data stored in localstorage before upgrading to Crosswalk. Crosswalk now supports this by default: https://crosswalk-project.org/blog/crosswalk-15-beta.html (Preserving webview local storage data). Therefor this plugin is deprecated. 

Regards,

Jeroen

**Comment by TechGuyVN** [comment]
Hi Redfire,

did you trying a newst crosswalk, currently i use ionic & crosswalk 18+, but problem still occur.
i try to build with crosswalk 15 like you said but it seem error:

> :compileArmv7DebugJavaWithJavac/Users/macpro/Documents/Developer/MobileEnterPrise/platforms/android/src/org/crosswalk/engine/XWalkCordovaHttpAuthHandler.java:22: error: cannot find symbol
> import org.xwalk.core.XWalkHttpAuthHandler;
>                      ^
>   symbol:   class XWalkHttpAuthHandler
>   location: package org.xwalk.core
> /Users/macpro/Documents/Developer/MobileEnterPrise/platforms/android/src/org/crosswalk/engine/XWalkCordovaHttpAuthHandler.java:30: error: cannot find symbol
>     private final XWalkHttpAuthHandler handler;
>                   ^
>   symbol:   class XWalkHttpAuthHandler
>   location: class XWalkCordovaHttpAuthHandler
> /Users/macpro/Documents/Developer/MobileEnterPrise/platforms/android/src/org/crosswalk/engine/XWalkCordovaHttpAuthHandler.java:32: error: cannot find symbol
>     public XWalkCordovaHttpAuthHandler(XWalkHttpAuthHandler handler) {
>                                        ^
>   symbol:   class XWalkHttpAuthHandler
>   location: class XWalkCordovaHttpAuthHandler
> /Users/macpro/Documents/Developer/MobileEnterPrise/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:33: error: cannot find symbol
> import org.xwalk.core.XWalkHttpAuthHandler;

Can you take a look for this, many thanks to you :)

**Comment by jeroenmaas** [comment]
Hi,

Crosswalk 18+ should also like 15 contain the logic to update existing localstorage to crosswalk localstorage. So you can just use the latest crosswalk and not need this plugin anymore.

The builderrors you posted are of using latest cordova crosswalk plugin with old crosswalk versions. Those won't mix well.

I'm going to close this issue. Going to crosswalk documentation/forums/issue tracker might help you realize your goal.

Regards,

Jeroen Maas
